import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
export default function Home() {
    return (_jsxs("div", { className: "fade-in", children: [_jsxs("section", { className: "relative overflow-hidden rounded-2xl bg-white border shadow-md", children: [_jsx("div", { "aria-hidden": true, className: "absolute inset-0 opacity-10 mix-blend-multiply", style: {
                            backgroundImage: 'url(/logo.jpg)',
                            backgroundSize: 'contain',
                            backgroundRepeat: 'no-repeat',
                            backgroundPosition: 'right -10% top -10%',
                        } }), _jsx("div", { className: "relative px-6 py-12 md:px-12 md:py-16", children: _jsxs("div", { className: "max-w-2xl", children: [_jsx("h1", { className: "text-4xl md:text-5xl font-bold leading-tight", children: "Welcome to Learnify" }), _jsx("p", { className: "mt-4 text-lg text-neutral-700", children: "Learnify is your all-in-one academic platform where teachers design interactive courses and students explore, enroll, and track their learning journey \u2014 from credits and progress to schedules and past achievements." }), _jsxs("div", { className: "mt-6 flex flex-wrap gap-3", children: [_jsx(Link, { to: "/student", className: "btn-primary", children: "Enter Student Portal" }), _jsx(Link, { to: "/teacher", className: "btn-ghost", children: "Enter Teacher Portal" })] }), _jsx("p", { className: "mt-3 text-sm text-neutral-600", children: "* Sign-up and authentication features coming soon." })] }) })] }), _jsxs("section", { className: "grid gap-6 md:grid-cols-3 mt-8", children: [_jsxs("div", { className: "card", children: [_jsx("div", { className: "text-sm text-neutral-600", children: "For Teachers" }), _jsx("h3", { className: "text-xl font-semibold mt-1", children: "Create & Manage Courses" }), _jsx("p", { className: "text-neutral-700 mt-2", children: "Design, publish, and manage your classes and monitor student engagement." })] }), _jsxs("div", { className: "card", children: [_jsx("div", { className: "text-sm text-neutral-600", children: "For Students" }), _jsx("h3", { className: "text-xl font-semibold mt-1", children: "Discover & Enroll Easily" }), _jsx("p", { className: "text-neutral-700 mt-2", children: "Explore courses, enroll instantly, and stay on top of your learning progress." })] }), _jsxs("div", { className: "card", children: [_jsx("div", { className: "text-sm text-neutral-600", children: "Beautiful & Academic" }), _jsx("h3", { className: "text-xl font-semibold mt-1", children: "Inspired by Excellence" }), _jsx("p", { className: "text-neutral-700 mt-2", children: "Elegant crimson palette and timeless typography that reflect academic prestige." })] })] })] }));
}
